[
  {
    "top": "newtop",
    "bottom": "Wide Blue Jeans",
    "outer": null,
    "onepiece": null,
    "colors": ["navy"],
    "colorScore": null,
    "min_temp": 5.0,
    "max_temp": 20.0,
    "type": "match",
    "spring": true,
    "summer": false,
    "autumn": true,
    "winter": true,
    "styles": ["plain", "plain"]
  },
  {
    "top": "newtop",
    "bottom": "Fun shorts",
    "outer": null,
    "onepiece": null,
    "colors": ["navy", "soft white", "warm gray"],
    "colorScore": null,
    "min_temp": 12.5,
    "max_temp": 30.0,
    "type": "match",
    "spring": true,
    "summer": false,
    "autumn": false,
    "winter": false,
    "styles": ["plain", "patterned"]
  },
  {
    "top": "newtop",
    "bottom": "White shorts",
    "outer": null,
    "onepiece": null,
    "colors": ["navy", "soft white"],
    "colorScore": null,
    "min_temp": 12.5,
    "max_temp": 30.0,
    "type": "match",
    "spring": true,
    "summer": false,
    "autumn": false,
    "winter": false,
    "styles": ["plain", "patterned"]
  },
  {
    "top": "newtop",
    "bottom": "Wide Blue Jeans",
    "outer": "Camel coat",
    "onepiece": null,
    "colors": ["navy", "terracotta"],
    "colorScore": null,
    "min_temp": 9.5,
    "max_temp": 21.0,
    "type": "match",
    "spring": true,
    "summer": false,
    "autumn": true,
    "winter": true,
    "styles": ["plain", "plain", "plain"]
  },
  {
    "top": "newtop",
    "bottom": "Fun shorts",
    "outer": "Camel coat",
    "onepiece": null,
    "colors": ["navy", "soft white", "warm gray", "terracotta"],
    "colorScore": null,
    "min_temp": 13.75,
    "max_temp": 31.0,
    "type": "match",
    "spring": true,
    "summer": false,
    "autumn": false,
    "winter": false,
    "styles": ["plain", "patterned", "plain"]
  },
  {
    "top": "newtop",
    "bottom": "White shorts",
    "outer": "Camel coat",
    "onepiece": null,
    "colors": ["navy", "soft white", "terracotta"],
    "colorScore": null,
    "min_temp": 13.75,
    "max_temp": 31.0,
    "type": "match",
    "spring": true,
    "summer": false,
    "autumn": false,
    "winter": false,
    "styles": ["plain", "patterned", "plain"]
  }
]
