
exports.colorPalettes = [
  ["Cream", "Camel", "Tan", "White", "Gold", "Olive Green", "Brown"],
  ["Cream", "Camel", "Tan", "White", "Maroon", "Gold", "Olive Green", "Brown", "Green"],
  ["Cream", "Camel", "Tan", "White", "Gold", "Navy", "Light Blue", "Dark Blue", "Brown"],
  ["Peach", "Cream", "Pink", "Lavender", "Light Blue", "White", "Silver"],
  ["Fuchsia", "Pink", "Magenta", "Lavender", "Lilac", "White"],
  ["Dark Blue", "Navy", "Light Blue", "Silver", "White", "Lavender", "Lilac"],
  ["Forest Green", "Green", "Olive Green", "Kharki", "Cream", "Tan", "Brown"],
  ["Red", "Orange", "Gold", "Peach", "Cream", "Camel", "White"],
  ["Black", "Grey", "Silver", "White", "Red", "Maroon", "Gold"],
  ["Coral", "Peach", "Pink", "Cream", "Gold", "Orange", "White"],
  ["Purple", "Lavender", "Lilac", "Pink", "Silver", "White"],
  ["Olive Green", "Green", "Turquoise", "Teal", "Cream", "White"],
  ["Gold", "Cream", "Camel", "Tan", "Brown", "Peach", "White"],
  ["Navy", "Dark Blue", "Silver", "Lavender", "Light Blue", "Cream", "White"],
  ["Magenta", "Fuchsia", "Pink", "Purple", "Lilac", "Lavender", "White"],
  ["Camel", "Cream", "Peach", "Tan", "White", "Brown", "Gold"],
  ["Turquoise", "Teal", "Green", "Lime Green", "White", "Light Blue", "Silver"],
  ["Lavender", "Lilac", "Light Blue", "White", "Silver", "Fuchsia"],
  ["Maroon", "Red", "Gold", "Brown", "Camel", "Cream", "White"],
  ["Orange", "Peach", "Yellow", "Coral", "Pink", "White"],
  ["Tan", "Camel", "Kharki", "Olive Green", "Brown", "Cream", "White"],
  ["Black", "Maroon", "Red", "Gold", "Cream", "Brown"],
  ["Green", "Lime Green", "Turquoise", "Teal", "Cream", "White"],
  ["Peach", "Pink", "Coral", "Fuchsia", "Lavender", "Cream"],
  ["Silver", "Grey", "Lavender", "White", "Light Blue", "Lilac"],
  ["Dark Blue", "Light Blue", "Turquoise", "Teal", "White", "Silver"],
  ["Camel", "Tan", "Kharki", "Olive Green", "Cream", "Gold", "White"],
  ["Lavender", "Lilac", "Purple", "Fuchsia", "Pink", "Cream"],
  ["Navy", "Dark Blue", "Light Blue", "Silver", "White", "Lavender", "Cream"],
  ["Forest Green", "Green", "Olive Green", "Turquoise", "Light Blue", "White"],
  ["Coral", "Peach", "Pink", "Cream", "White", "Lavender"],
  ["Magenta", "Fuchsia", "Purple", "Pink", "Lavender", "Lilac", "Cream"],
  ["Gold", "Orange", "Peach", "Camel", "Cream", "White"],
  ["Tan", "Beige", "Brown", "Kharki", "Olive Green", "Cream", "White"],
  ["Red", "Pink", "Peach", "White", "Lavender", "Magenta"],
  ["Silver", "Light Blue", "Lavender", "White", "Lilac"],
  ["Olive Green", "Green", "Kharki", "Tan", "Camel", "Cream"],
  ["Pink", "Fuchsia", "Magenta", "Lavender", "Lilac", "Cream", "White"],
  ["Dark Blue", "Navy", "Lavender", "Silver", "White", "Light Blue"],
  ["Yellow", "Peach", "Orange", "White", "Cream", "Coral"],
  ["Purple", "Lilac", "Lavender", "Pink", "Silver", "White"],
  ["Cream", "Camel", "Peach", "White", "Gold", "Tan", "Olive Green"],
  ["Light Blue", "Lavender", "Lilac", "White", "Silver", "Fuchsia", "Cream"],
  ["Fuchsia", "Pink", "Lavender", "Lilac", "White", "Silver"],
  ["Green", "Lime Green", "Olive Green", "Kharki", "Cream", "White"],
  ["Red", "Orange", "Yellow", "Peach", "Pink", "Cream"],
  ["Forest Green", "Green", "Turquoise", "Olive Green", "Light Blue", "White"],
  ["Maroon", "Red", "Pink", "Gold", "White", "Cream", "Brown"],
  ["Beige", "Cream", "Peach", "Pink", "White", "Light Blue", "Gold"],
  ["Navy", "Dark Blue", "Silver", "Lavender", "White", "Gold", "Light Blue"]
];

